export const projects = [
  {
    title: 'MERN Blog',
    description: "Build a Full Stack MERN Application for posting interesting events in your life. Learn React, Node.js, Express & MongoDB.",
    image: '../images/MERN.webp',
    tags: ['MongoDB', 'Express', 'React', 'Node', 'Redux'],
    source: 'https://github.com/Vasyl-Pavlenko/front-mern-blog',
    visit: 'https://front-mern-blog.vercel.app/',
    id: 0,
  },
  {
    title: 'Bank App',
    description: "Learn advanced React and CSS topics while building a bank application.",
    image: '../images/bank.webp',
    tags: ['React', 'JavaScript', 'Tailwind'],
    source: 'https://github.com/Vasyl-Pavlenko/bank',
    visit: 'https://vasyl-pavlenko.github.io/bank/',
    id: 1,
  },
  {
    title: 'Restourant App',
    description: "Single Page Application for restourant",
    image: '../images/restourant.webp',
    tags: ['React', 'HTML', 'CSS', 'BEM'],
    source: 'https://github.com/Vasyl-Pavlenko/restourant',
    visit: 'https://vasyl-pavlenko.github.io/restourant/',
    id: 2,
  },
  {
    title: 'GPT-3 Landing',
    description: "Single Page Application for DPT-3 presentation",
    image: '../images/gpt-3.webp',
    tags: ['React', 'HTML', 'CSS', 'BEM'],
    source: 'https://github.com/Vasyl-Pavlenko/ui_ux_gpt3/tree/main',
    visit: 'https://vasyl-pavlenko.github.io/ui_ux_gpt3/',
    id: 3,
  },
  {
    title: 'Todo App',
    description: "The React Todo App is a simple and intuitive task management application built using React. Users can create, edit, and delete tasks, set due dates, mark tasks as completed, and filter tasks based on their status. The app has a clean and minimalist user interface, making it easy for users to manage their to-do list efficiently",
    image: '../images/Todo.webp',
    tags: ['React', 'JS', 'TS', 'HTML', 'CSS'],
    source: 'https://github.com/Vasyl-Pavlenko/react__TODO',
    visit: 'https://vasyl-pavlenko.github.io/react__TODO/',
    id: 4,
  },
  {
    title: '2048 JS Game',
    description: "This is a simple implementation of the popular game 2048 using JavaScript and HTML/CSS. The game board is a 4x4 grid, and the goal is to reach the number 2048 by merging tiles with the same numbers",
    image: '../images/2048.webp',
    tags: ['JS', 'HTML', 'CSS'],
    source: 'https://github.com/Vasyl-Pavlenko/js_2048',
    visit: 'https://vasyl-pavlenko.github.io/js_2048/',
    id: 5,
  },
  {
    title: 'Markdown',
    description: "Simple markdown text converter",
    image: '../images/Markdown.webp',
    tags: ['React'],
    source: 'https://github.com/Vasyl-Pavlenko/markdown-converter',
    visit: 'https://vasyl-pavlenko.github.io/markdown-converter/',
    id: 6,
  },
  {
    title: 'Simple random quote machine',
    description: "Simple random quote machine with pure React",
    image: '../images/Quotes.webp',
    tags: ['React', 'CSS'],
    source: 'https://github.com/Vasyl-Pavlenko/quotes-generator',
    visit: 'https://vasyl-pavlenko.github.io/quotes-generator/',
    id: 7,
  },
  {
    title: 'React calculator',
    description: "Dekstop calcutor with pure React",
    image: '../images/Calculator.webp',
    tags: ['React'],
    source: 'https://github.com/Vasyl-Pavlenko/react-calculator',
    visit: 'https://vasyl-pavlenko.github.io/react-calculator/',
    id: 8,
  },
  {
    title: 'Drum Machine',
    description: "Drum machine with few features",
    image: '../images/Drum.webp',
    tags: ['React', 'CSS'],
    source: 'https://github.com/Vasyl-Pavlenko/drum-machine',
    visit: 'https://vasyl-pavlenko.github.io/drum-machine/',
    id: 9,
  },
  {
    title: 'React clock',
    description: "A desktop clock built with React.",
    image: '../images/Clock.webp',
    tags: ['React'],
    source: 'https://github.com/Vasyl-Pavlenko/react-clock',
    visit: 'https://vasyl-pavlenko.github.io/react-clock/',
    id: 10,
  },
  {
    title: 'My bike Landing',
    description: "One-page site for advertising a bike shop, developed using HTML, CSS, Sass, and a bit of JavaScript.",
    image: '../images/BIKE.webp',
    tags: ['HTML', 'CSS', 'Sass', 'JS', 'BEM'],
    source: 'https://github.com/Vasyl-Pavlenko/layout-my-bike',
    visit: 'https://vasyl-pavlenko.github.io/layout-my-bike/',
    id: 11,
  },
  {
    title: 'AIR Landing',
    description: "One-page site for a full-service creative agency, responsive for mobile, tablet, and desktop",
    image: '../images/AIR.webp',
    tags: ['HTML', 'CSS', 'Sass', 'JS'],
    source: 'https://github.com/Vasyl-Pavlenko/layout-dia',
    visit: 'https://vasyl-pavlenko.github.io/layout_dia/',
    id: 12,
  },
];

export const TimeLineData = [
  { year: 2015, text: 'Real estate agent', },
  { year: 2020, text: 'Account Manager', },
  { year: 2022, text: 'Frontend Developer', },
];